packages:
  base: !include common/zehnder_base.yaml

esphome:
  on_boot:
    priority: 600
    then:
      - logger.log:
          level: WARN
          format: "WARNING: Fallback configuration is used for zehnder comfoair. Please include the configuration specific to your firmware version!"