# Configuration for devices with the 3.x.x firmware.

packages:
  base: !include common/zehnder_base.yaml
  common: !include common/zehnder_common_23.yaml

uart:
  baud_rate: 9600

sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    id: zehnder_int_sensor_error
    internal: true
    register_type: holding
    address: 0x190

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    id: zehnder_int_actuator_error
    internal: true
    register_type: holding
    address: 0x192

text_sensor:
  - platform: template
    name: "Status"
    id: zehnder_status
    icon: mdi:clipboard-text
    entity_category: "diagnostic"
    lambda: |-
        if (id(zehnder_int_sensor_error) > 0 || id(zehnder_int_actuator_error) > 0) {
          return std::string("Error");
        } else {
          return std::string("Normal");
        };

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Heat exchanger type"
    id: zehnder_heat_exchanger_type
    register_type: holding
    entity_category: "diagnostic"
    address: 0x158
    raw_encode: HEXBYTES
    lambda: |-
        uint16_t value = modbus::helpers::word_from_hex_str(x, 0);
        switch (value) {
          case 0: return std::string("HRV");
          case 1: return std::string("ERV");
          default: return std::string("Unknown (") + std::to_string(value) + ")";
        }
        return x;

binary_sensor:
- platform: modbus_controller
  modbus_controller_id: modbus_device
  id: zehnder_humidity_control 
  name: "Comfort Humidity control"
  entity_category: diagnostic
  address: 0x159
  register_type: holding