# Configuration for devices with the 3.x.x firmware.

packages:
  base: !include common/zehnder_base.yaml
  common: !include common/zehnder_common_23.yaml

uart:
  baud_rate: 9600

text_sensor:
  - platform: template
    name: "Status"
    id: zehnder_status
    icon: mdi:clipboard-text
    entity_category: "diagnostic"
    lambda: |-
        uint16_t value = 10;
        switch (value) {
          case 0: return std::string("Error");
          case 1: return std::string("Initializing");
          case 2: return std::string("Self-Test");
          case 3: return std::string("Waiting for user input");
          case 10: return std::string("Normal");
          case 11: case 20: return std::string("Standby");
          case 40: case 41: case 42: return std::string("Maintenance Mode");
          default: return std::string("Unknown (") + std::to_string(value) + ")";
        }
        return x;

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Heat exchanger type"
    id: zehnder_heat_exchanger_type
    register_type: holding
    entity_category: "diagnostic"
    address: 0x158
    raw_encode: HEXBYTES
    lambda: |-
        uint16_t value = modbus::helpers::word_from_hex_str(x, 0);
        switch (value) {
          case 0: return std::string("HRV");
          case 1: return std::string("ERV");
          default: return std::string("Unknown (") + std::to_string(value) + ")";
        }
        return x;

binary_sensor:
- platform: modbus_controller
  modbus_controller_id: modbus_device
  id: zehnder_humidity_control 
  name: "Comfort Humidity control"
  entity_category: diagnostic
  address: 0x159
  register_type: holding