packages:
  base: !include common/zehnder_base.yaml

esphome:
  on_boot:
    priority: 600 
    then:
      - delay: 10s
      - logger.log:
          level: WARN
          format: "Fallback configuration is used for zehnder comfoair. Please use the configuration specific to your firmware version!"